relativeURLs = true
title = "Pedro Cubillos"
theme = "mytheme"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "PhD Student in Economics, University College London"
    logo = "yo.jpg"
    email = "pedro.cubillos.24@ucl.ac.uk"
    phone = "+44 7771642488"
    twitter = "https://x.com/ppcubillosr"
    googlescholar = "https://scholar.google.com/citations?user=TX1uT_oAAAAJ&hl=en"
    
