relativeURLs = true
title = "Pedro Cubillos"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "PhD Student in Economics, University College London"
    logo = "Rao_headshot_berkeley.jpg" 
    
